/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import java.awt.Color;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;

public class MainWindow extends javax.swing.JFrame {
    
    /**
     * Creates new form MainFrame
     */
    public MainWindow() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        halreg = new javax.swing.JLayeredPane();
        ucapan = new javax.swing.JLabel();
        namabengkel = new javax.swing.JLabel();
        akronim = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        textnama = new javax.swing.JTextField();
        textalamat = new javax.swing.JTextField();
        angkart = new javax.swing.JTextField();
        RT = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        RW = new javax.swing.JLabel();
        angkarw = new javax.swing.JTextField();
        kelurahan = new javax.swing.JLabel();
        textkelurahan = new javax.swing.JTextField();
        kecamatan = new javax.swing.JLabel();
        textkecamatan = new javax.swing.JTextField();
        textkota = new javax.swing.JTextField();
        kota = new javax.swing.JLabel();
        notelp = new javax.swing.JLabel();
        angkatelp = new javax.swing.JTextField();
        textasal = new javax.swing.JTextField();
        textplat = new javax.swing.JTextField();
        platno = new javax.swing.JLabel();
        tipe = new javax.swing.JLabel();
        angkaplat = new javax.swing.JTextField();
        textplat2 = new javax.swing.JTextField();
        kelurahantest = new javax.swing.JLabel();
        rttest = new javax.swing.JLabel();
        rwtest = new javax.swing.JLabel();
        kecamatantest = new javax.swing.JLabel();
        kotatest = new javax.swing.JLabel();
        plattexttest = new javax.swing.JLabel();
        angkaplattest = new javax.swing.JLabel();
        notelptest = new javax.swing.JLabel();
        namatest = new javax.swing.JLabel();
        bg_putih1 = new javax.swing.JLabel();
        tombolkonfirmasi = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        halkonfirmasi = new javax.swing.JLayeredPane();
        ctextnama = new javax.swing.JLabel();
        ctextcatatan = new javax.swing.JLabel();
        infonama = new javax.swing.JLabel();
        cnama = new javax.swing.JLabel();
        bgnama = new javax.swing.JLabel();
        infoalamat = new javax.swing.JLabel();
        calamat = new javax.swing.JLabel();
        bgalamat = new javax.swing.JLabel();
        infort = new javax.swing.JLabel();
        crt = new javax.swing.JLabel();
        inforw = new javax.swing.JLabel();
        crw = new javax.swing.JLabel();
        bgrtrw = new javax.swing.JLabel();
        infokelurahan = new javax.swing.JLabel();
        ckelurahan = new javax.swing.JLabel();
        bgkelurahan = new javax.swing.JLabel();
        infokecamatan = new javax.swing.JLabel();
        ckecamatan = new javax.swing.JLabel();
        bgkecamatan = new javax.swing.JLabel();
        infokabkota = new javax.swing.JLabel();
        ckabkota = new javax.swing.JLabel();
        bgkabkota = new javax.swing.JLabel();
        infonotelp = new javax.swing.JLabel();
        cnotelp1 = new javax.swing.JLabel();
        bgnotelp = new javax.swing.JLabel();
        infotipe = new javax.swing.JLabel();
        ctipe = new javax.swing.JLabel();
        bgtipe = new javax.swing.JLabel();
        infoplat = new javax.swing.JLabel();
        ctextplat1 = new javax.swing.JLabel();
        ctextplat2 = new javax.swing.JLabel();
        cangkaplat = new javax.swing.JLabel();
        bgplat = new javax.swing.JLabel();
        persetujuan = new javax.swing.JCheckBox();
        catatan1 = new javax.swing.JLabel();
        catatan2 = new javax.swing.JLabel();
        kembali = new javax.swing.JButton();
        ketkonfirmasi = new javax.swing.JLabel();
        konfirmasi2 = new javax.swing.JButton();
        bg_konfirmasi = new javax.swing.JLabel();
        bginfo = new javax.swing.JLabel();
        bgtitle = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        halpenutup = new javax.swing.JLayeredPane();
        judulpenutup = new javax.swing.JLabel();
        terimakasih = new javax.swing.JLabel();
        bgjudul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsi = new javax.swing.JTextArea();
        infoprogress = new javax.swing.JLabel();
        progressred = new javax.swing.JProgressBar();
        logo1 = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        bg4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrasi Pelanggan \"BBM\"");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        halreg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ucapan.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        ucapan.setForeground(new java.awt.Color(0, 204, 255));
        ucapan.setText("WELCOME TO");
        halreg.add(ucapan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 110, 20));

        namabengkel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        namabengkel.setForeground(new java.awt.Color(0, 204, 255));
        namabengkel.setText("BENGKEL  BM");
        halreg.add(namabengkel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 120, 20));

        akronim.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 20)); // NOI18N
        akronim.setForeground(new java.awt.Color(0, 204, 255));
        akronim.setText("(Benerin Motor)");
        halreg.add(akronim, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 110, 20));

        nama.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setText("Nama");
        halreg.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 50, 20));

        textnama.setBorder(new LineBorder(Color.GRAY, 2));
        textnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textnamaActionPerformed(evt);
            }
        });
        textnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textnamaKeyReleased(evt);
            }
        });
        halreg.add(textnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 190, 30));

        textalamat.setBorder(new LineBorder(Color.GRAY, 2));
        halreg.add(textalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 190, 30));

        angkart.setBorder(new LineBorder(Color.GRAY, 2));
        angkart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkartActionPerformed(evt);
            }
        });
        angkart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                angkartKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                angkartKeyTyped(evt);
            }
        });
        halreg.add(angkart, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 60, 30));

        RT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RT.setForeground(new java.awt.Color(255, 255, 255));
        RT.setText("RT");
        halreg.add(RT, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 20, 20));

        alamat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        alamat.setForeground(new java.awt.Color(255, 255, 255));
        alamat.setText("Alamat");
        halreg.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 50, 20));

        RW.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RW.setForeground(new java.awt.Color(255, 255, 255));
        RW.setText("RW");
        halreg.add(RW, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 30, 20));

        angkarw.setBorder(new LineBorder(Color.GRAY, 2));
        angkarw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkarwActionPerformed(evt);
            }
        });
        angkarw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                angkarwKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                angkarwKeyTyped(evt);
            }
        });
        halreg.add(angkarw, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 60, 30));

        kelurahan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kelurahan.setForeground(new java.awt.Color(255, 255, 255));
        kelurahan.setText("Kelurahan");
        halreg.add(kelurahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 70, 20));

        textkelurahan.setBorder(new LineBorder(Color.GRAY, 2));
        textkelurahan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textkelurahanKeyReleased(evt);
            }
        });
        halreg.add(textkelurahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 190, 30));

        kecamatan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kecamatan.setForeground(new java.awt.Color(255, 255, 255));
        kecamatan.setText("Kecamatan");
        halreg.add(kecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 70, 20));

        textkecamatan.setBorder(new LineBorder(Color.GRAY, 2));
        textkecamatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textkecamatanActionPerformed(evt);
            }
        });
        textkecamatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textkecamatanKeyReleased(evt);
            }
        });
        halreg.add(textkecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 190, 30));

        textkota.setBorder(new LineBorder(Color.GRAY, 2));
        textkota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textkotaKeyReleased(evt);
            }
        });
        halreg.add(textkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 190, 30));

        kota.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kota.setForeground(new java.awt.Color(255, 255, 255));
        kota.setText("Kab/Kota");
        halreg.add(kota, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 70, 20));

        notelp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        notelp.setForeground(new java.awt.Color(255, 255, 255));
        notelp.setText("No. Telepon");
        halreg.add(notelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        angkatelp.setForeground(new java.awt.Color(153, 153, 153));
        angkatelp.setText("08xxxxxxxxx");
        angkatelp.setBorder(new LineBorder(Color.GRAY, 2));
        angkatelp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                angkatelpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                angkatelpFocusLost(evt);
            }
        });
        angkatelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkatelpActionPerformed(evt);
            }
        });
        angkatelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                angkatelpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                angkatelpKeyTyped(evt);
            }
        });
        halreg.add(angkatelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 190, 30));

        textasal.setBorder(new LineBorder(Color.GRAY, 2));
        textasal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textasalActionPerformed(evt);
            }
        });
        halreg.add(textasal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 190, 30));

        textplat.setBorder(new LineBorder(Color.GRAY, 2));
        textplat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textplatActionPerformed(evt);
            }
        });
        textplat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textplatKeyReleased(evt);
            }
        });
        halreg.add(textplat, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 40, 30));

        platno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        platno.setForeground(new java.awt.Color(255, 255, 255));
        platno.setText("No. Plat");
        halreg.add(platno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 80, 20));

        tipe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tipe.setForeground(new java.awt.Color(255, 255, 255));
        tipe.setText("Keluhan Singkat");
        halreg.add(tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 100, 20));

        angkaplat.setBorder(new LineBorder(Color.GRAY, 2));
        angkaplat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angkaplatActionPerformed(evt);
            }
        });
        angkaplat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                angkaplatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                angkaplatKeyTyped(evt);
            }
        });
        halreg.add(angkaplat, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 50, 30));

        textplat2.setBorder(new LineBorder(Color.GRAY, 2));
        textplat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textplat2ActionPerformed(evt);
            }
        });
        textplat2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textplat2KeyReleased(evt);
            }
        });
        halreg.add(textplat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 40, 30));

        kelurahantest.setBackground(new java.awt.Color(255, 255, 255));
        kelurahantest.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        kelurahantest.setForeground(new java.awt.Color(255, 0, 0));
        halreg.add(kelurahantest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 160, 20));

        rttest.setBackground(new java.awt.Color(255, 255, 255));
        rttest.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        rttest.setForeground(new java.awt.Color(255, 0, 0));
        halreg.add(rttest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 160, 20));

        rwtest.setBackground(new java.awt.Color(255, 255, 255));
        rwtest.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        rwtest.setForeground(new java.awt.Color(255, 0, 0));
        halreg.add(rwtest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 160, 20));

        kecamatantest.setBackground(new java.awt.Color(255, 255, 255));
        kecamatantest.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        kecamatantest.setForeground(new java.awt.Color(255, 0, 0));
        halreg.add(kecamatantest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 160, 20));

        kotatest.setBackground(new java.awt.Color(255, 255, 255));
        kotatest.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        kotatest.setForeground(new java.awt.Color(255, 0, 0));
        halreg.add(kotatest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 160, 20));

        plattexttest.setBackground(new java.awt.Color(255, 255, 255));
        plattexttest.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        plattexttest.setForeground(new java.awt.Color(255, 0, 0));
        halreg.add(plattexttest, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 470, 150, 20));

        angkaplattest.setBackground(new java.awt.Color(255, 255, 255));
        angkaplattest.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        angkaplattest.setForeground(new java.awt.Color(255, 0, 0));
        halreg.add(angkaplattest, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 150, 20));

        notelptest.setBackground(new java.awt.Color(255, 255, 255));
        notelptest.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        notelptest.setForeground(new java.awt.Color(255, 0, 0));
        halreg.add(notelptest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 160, 20));

        namatest.setBackground(new java.awt.Color(255, 255, 255));
        namatest.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        namatest.setForeground(new java.awt.Color(255, 0, 0));
        halreg.add(namatest, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 160, 20));

        bg_putih1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_gray10%.png"))); // NOI18N
        halreg.add(bg_putih1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 490, 490));

        tombolkonfirmasi.setBackground(new java.awt.Color(255, 255, 255));
        tombolkonfirmasi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tombolkonfirmasi.setForeground(new java.awt.Color(0, 0, 0));
        tombolkonfirmasi.setText("Konfirmasi");
        tombolkonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolkonfirmasiActionPerformed(evt);
            }
        });
        halreg.add(tombolkonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, 130, 40));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        halreg.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, -1, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        halreg.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, -1, -1));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg.jpg"))); // NOI18N
        halreg.add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 690, 540));

        getContentPane().add(halreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 540));

        halkonfirmasi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ctextnama.setBackground(new java.awt.Color(0, 0, 0));
        ctextnama.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ctextnama.setForeground(new java.awt.Color(255, 255, 255));
        ctextnama.setText("Apakah Anda yakin Data Yang Dimasukkan Benar?");
        halkonfirmasi.add(ctextnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 41));

        ctextcatatan.setBackground(new java.awt.Color(0, 0, 0));
        ctextcatatan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ctextcatatan.setForeground(new java.awt.Color(255, 255, 255));
        ctextcatatan.setText("Silahkan Cek Kembali Data Anda");
        halkonfirmasi.add(ctextcatatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        infonama.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        infonama.setForeground(new java.awt.Color(255, 255, 255));
        infonama.setText("Nama");
        halkonfirmasi.add(infonama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        cnama.setBackground(new java.awt.Color(255, 255, 255));
        cnama.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cnama.setForeground(new java.awt.Color(255, 255, 255));
        halkonfirmasi.add(cnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 290, 20));

        bgnama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_darkgray.png"))); // NOI18N
        halkonfirmasi.add(bgnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 370, 20));

        infoalamat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        infoalamat.setForeground(new java.awt.Color(255, 255, 255));
        infoalamat.setText("Alamat");
        halkonfirmasi.add(infoalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        calamat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        calamat.setForeground(new java.awt.Color(255, 255, 255));
        halkonfirmasi.add(calamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 290, 20));

        bgalamat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_darkgray.png"))); // NOI18N
        halkonfirmasi.add(bgalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 370, 20));

        infort.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infort.setForeground(new java.awt.Color(255, 255, 255));
        infort.setText("RT");
        halkonfirmasi.add(infort, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        crt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        crt.setForeground(new java.awt.Color(255, 255, 255));
        halkonfirmasi.add(crt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 50, 20));

        inforw.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        inforw.setForeground(new java.awt.Color(255, 255, 255));
        inforw.setText("RW");
        halkonfirmasi.add(inforw, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        crw.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        crw.setForeground(new java.awt.Color(255, 255, 255));
        halkonfirmasi.add(crw, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 50, 20));

        bgrtrw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_darkgray.png"))); // NOI18N
        halkonfirmasi.add(bgrtrw, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 180, 20));

        infokelurahan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infokelurahan.setForeground(new java.awt.Color(255, 255, 255));
        infokelurahan.setText("Kelurahan");
        halkonfirmasi.add(infokelurahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        ckelurahan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckelurahan.setForeground(new java.awt.Color(255, 255, 255));
        halkonfirmasi.add(ckelurahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 230, 20));

        bgkelurahan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_darkgray.png"))); // NOI18N
        halkonfirmasi.add(bgkelurahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 340, 20));

        infokecamatan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infokecamatan.setForeground(new java.awt.Color(255, 255, 255));
        infokecamatan.setText("Kecamatan");
        halkonfirmasi.add(infokecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        ckecamatan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckecamatan.setForeground(new java.awt.Color(255, 255, 255));
        halkonfirmasi.add(ckecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 230, 20));

        bgkecamatan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_darkgray.png"))); // NOI18N
        halkonfirmasi.add(bgkecamatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 340, 20));

        infokabkota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        infokabkota.setForeground(new java.awt.Color(255, 255, 255));
        infokabkota.setText("Kab/Kota");
        halkonfirmasi.add(infokabkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        ckabkota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ckabkota.setForeground(new java.awt.Color(255, 255, 255));
        halkonfirmasi.add(ckabkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 230, 20));

        bgkabkota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_darkgray.png"))); // NOI18N
        halkonfirmasi.add(bgkabkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 340, 20));

        infonotelp.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        infonotelp.setForeground(new java.awt.Color(255, 255, 255));
        infonotelp.setText("No.  Telp.");
        halkonfirmasi.add(infonotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, 20));

        cnotelp1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cnotelp1.setForeground(new java.awt.Color(255, 255, 255));
        halkonfirmasi.add(cnotelp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 280, 20));

        bgnotelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_darkgray.png"))); // NOI18N
        halkonfirmasi.add(bgnotelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 370, 20));

        infotipe.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        infotipe.setForeground(new java.awt.Color(255, 255, 255));
        infotipe.setText("Keluhan Singkat");
        halkonfirmasi.add(infotipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, 20));

        ctipe.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ctipe.setForeground(new java.awt.Color(255, 255, 255));
        halkonfirmasi.add(ctipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 280, 20));

        bgtipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_darkgray.png"))); // NOI18N
        halkonfirmasi.add(bgtipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 370, 20));

        infoplat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        infoplat.setForeground(new java.awt.Color(255, 255, 255));
        infoplat.setText("No. Plat");
        halkonfirmasi.add(infoplat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 70, 20));

        ctextplat1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ctextplat1.setForeground(new java.awt.Color(255, 255, 255));
        halkonfirmasi.add(ctextplat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 30, 20));

        ctextplat2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ctextplat2.setForeground(new java.awt.Color(255, 255, 255));
        halkonfirmasi.add(ctextplat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 50, 20));

        cangkaplat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cangkaplat.setForeground(new java.awt.Color(255, 255, 255));
        halkonfirmasi.add(cangkaplat, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 40, 20));

        bgplat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_darkgray.png"))); // NOI18N
        halkonfirmasi.add(bgplat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 370, 20));

        persetujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                persetujuanActionPerformed(evt);
            }
        });
        halkonfirmasi.add(persetujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 260, 40));

        catatan1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        catatan1.setForeground(new java.awt.Color(255, 255, 255));
        catatan1.setText("Saya yakin bahwa data yang telah saya");
        catatan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catatan1MouseClicked(evt);
            }
        });
        halkonfirmasi.add(catatan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        catatan2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        catatan2.setForeground(new java.awt.Color(255, 255, 255));
        catatan2.setText("isikan benar dan tanpa rekayasa");
        halkonfirmasi.add(catatan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, 20));

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        halkonfirmasi.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 90, 30));

        ketkonfirmasi.setForeground(new java.awt.Color(255, 0, 0));
        halkonfirmasi.add(ketkonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 130, 20));

        konfirmasi2.setText("Konfirmasi");
        konfirmasi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfirmasi2ActionPerformed(evt);
            }
        });
        konfirmasi2.setEnabled(false);
        halkonfirmasi.add(konfirmasi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 90, 30));

        bg_konfirmasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_putih.png"))); // NOI18N
        bg_konfirmasi.setVisible(false);
        halkonfirmasi.add(bg_konfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 130, 20));

        bginfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_textured.png"))); // NOI18N
        bginfo.setText("jLabel1");
        halkonfirmasi.add(bginfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 390, 390));

        bgtitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_gray_25transparent.png"))); // NOI18N
        bgtitle.setText("jLabel1");
        halkonfirmasi.add(bgtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 80));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg.jpg"))); // NOI18N
        halkonfirmasi.add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 540));

        getContentPane().add(halkonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 540));

        halpenutup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judulpenutup.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        judulpenutup.setForeground(new java.awt.Color(0, 153, 0));
        judulpenutup.setText("Registrasi Berhasil!");
        halpenutup.add(judulpenutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        terimakasih.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        terimakasih.setForeground(new java.awt.Color(0, 153, 0));
        terimakasih.setText(" Terima Kasih ^_^");
        halpenutup.add(terimakasih, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 180, -1));

        bgjudul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_putih.png"))); // NOI18N
        halpenutup.add(bgjudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 200, 70));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        deskripsi.setBackground(new java.awt.Color(153, 153, 153));
        deskripsi.setColumns(20);
        deskripsi.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        deskripsi.setLineWrap(true);
        deskripsi.setRows(5);
        deskripsi.setText("Silahkan Menuju Meja Registrasi untuk Pengecekan Dokumen Asli serta Penyerahan Kunci Kendaraan Anda");
        deskripsi.setWrapStyleWord(true);
        deskripsi.setEditable(false);
        jScrollPane1.setViewportView(deskripsi);

        halpenutup.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 330, 90));

        infoprogress.setText(" Halaman ini akan tertutup otomatis setelah beberapa saat...");
        halpenutup.add(infoprogress, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 320, 20));
        halpenutup.add(progressred, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 350, 20));

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        halpenutup.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg_gray.png"))); // NOI18N
        halpenutup.add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 530, 220));

        bg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg.jpg"))); // NOI18N
        halpenutup.add(bg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 540));

        getContentPane().add(halpenutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void textnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textnamaActionPerformed
        
    }//GEN-LAST:event_textnamaActionPerformed

    private void textnamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textnamaKeyReleased
        PatternCheck cekinput = new PatternCheck("^[A-Z a-z']{0,50}$", textnama.getText());
        namatest.setText(cekinput.cekinput("Nama"));
        if (!namatest.getText().equals("")) {
            textnama.setBorder(new LineBorder(Color.RED, 2));
        } else {
            textnama.setBorder(new LineBorder(Color.GRAY, 2));
        }
    }//GEN-LAST:event_textnamaKeyReleased

    private void angkartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkartActionPerformed
        
    }//GEN-LAST:event_angkartActionPerformed

    private void angkartKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angkartKeyReleased
        PatternCheck cekinput = new PatternCheck("^[0-9]{0,3}$", angkart.getText());
        rttest.setText(cekinput.cekinput("RT"));
        if (!rttest.getText().equals("")) {
            angkart.setBorder(new LineBorder(Color.RED, 2));
        } else {
            angkart.setBorder(new LineBorder(Color.GRAY, 2));
        }
    }//GEN-LAST:event_angkartKeyReleased

    private void angkarwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkarwActionPerformed
        
    }//GEN-LAST:event_angkarwActionPerformed

    private void angkarwKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angkarwKeyReleased
        PatternCheck cekinput = new PatternCheck("^[0-9]{0,3}$", angkarw.getText());
        rwtest.setText(cekinput.cekinput("RW"));
        if (!rwtest.getText().equals("")) {
            angkarw.setBorder(new LineBorder(Color.RED, 2));
        } else {
            angkarw.setBorder(new LineBorder(Color.GRAY, 2));
        }
    }//GEN-LAST:event_angkarwKeyReleased

    private void textkelurahanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textkelurahanKeyReleased
        PatternCheck cekinput = new PatternCheck("^[A-Z a-z]{0,100}$",textkelurahan.getText());
        kelurahantest.setText(cekinput.cekinput("Kelurahan"));
        if (!kelurahantest.getText().equals("")) {
            textkelurahan.setBorder(new LineBorder(Color.RED, 2));
        } else {
            textkelurahan.setBorder(new LineBorder(Color.GRAY, 2));
        }
    }//GEN-LAST:event_textkelurahanKeyReleased

    private void textkecamatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textkecamatanActionPerformed
        
    }//GEN-LAST:event_textkecamatanActionPerformed

    private void textkecamatanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textkecamatanKeyReleased
        PatternCheck cekinput = new PatternCheck("^[A-Z a-z]{0,100}$",textkecamatan.getText());
        kecamatantest.setText(cekinput.cekinput("Kecamatan"));
        if (!kecamatantest.getText().equals("")) {
            textkecamatan.setBorder(new LineBorder(Color.RED, 2));
        } else {
            textkecamatan.setBorder(new LineBorder(Color.GRAY, 2));
        }
    }//GEN-LAST:event_textkecamatanKeyReleased

    private void textkotaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textkotaKeyReleased
        PatternCheck cekinput = new PatternCheck("^[A-Z a-z]{0,100}$",textkota.getText());
        kotatest.setText(cekinput.cekinput("Kab/Kota"));
        if (!kotatest.getText().equals("")) {
            textkota.setBorder(new LineBorder(Color.RED, 2));
        } else {
            textkota.setBorder(new LineBorder(Color.GRAY, 2));
        }
    }//GEN-LAST:event_textkotaKeyReleased

    private void angkatelpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angkatelpKeyReleased
        PatternCheck cekinput = new PatternCheck("^[0-9]{10,13}$",angkatelp.getText());
        notelptest.setText(cekinput.cekinput("No. Telp."));
        if (!notelptest.getText().equals("")) {
            angkatelp.setBorder(new LineBorder(Color.RED, 2));
        } else {
            angkatelp.setBorder(new LineBorder(Color.GRAY, 2));
        }
    }//GEN-LAST:event_angkatelpKeyReleased

    private void textasalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textasalActionPerformed
        
    }//GEN-LAST:event_textasalActionPerformed

    private void textplatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textplatActionPerformed
        
    }//GEN-LAST:event_textplatActionPerformed

    private void textplatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textplatKeyReleased
        PatternCheck cekinput = new PatternCheck("^[A-Za-z]{0,2}$",textplat.getText());
        plattexttest.setText(cekinput.cekinput("Kode"));
        if (!plattexttest.getText().equals("")) {
            textplat.setBorder(new LineBorder(Color.RED, 2));
        } else {
            textplat.setBorder(new LineBorder(Color.GRAY, 2));
        }
    }//GEN-LAST:event_textplatKeyReleased

    private void angkaplatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkaplatActionPerformed
        
    }//GEN-LAST:event_angkaplatActionPerformed

    private void angkaplatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angkaplatKeyReleased
        PatternCheck cekinput = new PatternCheck("^[0-9]{0,4}$",angkaplat.getText());
        angkaplattest.setText(cekinput.cekinput("Nomor"));
        if (!angkaplattest.getText().equals("")) {
            angkaplat.setBorder(new LineBorder(Color.RED, 2));
        } else {
            angkaplat.setBorder(new LineBorder(Color.GRAY, 2));
        }
    }//GEN-LAST:event_angkaplatKeyReleased

    private void textplat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textplat2ActionPerformed
        
    }//GEN-LAST:event_textplat2ActionPerformed

    private void textplat2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textplat2KeyReleased
    }//GEN-LAST:event_textplat2KeyReleased

    private void tombolkonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolkonfirmasiActionPerformed
        if(verifyField()) {
            halreg.setVisible(false);
            halkonfirmasi.setVisible(true);
            halpenutup.setVisible(false);        
            cnama.setText(textnama.getText());
            calamat.setText(textalamat.getText());
            crt.setText(angkart.getText());
            crw.setText(angkarw.getText());
            ckelurahan.setText(textkelurahan.getText());
            ckecamatan.setText(textkecamatan.getText());
            ckabkota.setText(textkota.getText());
            cnotelp1.setText(angkatelp.getText());
            ctipe.setText(textasal.getText());
            ctextplat1.setText(textplat.getText());
            cangkaplat.setText(angkaplat.getText());
            ctextplat2.setText(textplat2.getText());   
        }
    }//GEN-LAST:event_tombolkonfirmasiActionPerformed
    
    private void persetujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_persetujuanActionPerformed
        if (persetujuan.isSelected()) {
            konfirmasi2.setEnabled(true);
            ketkonfirmasi.setText(" Silahkan klik konfirmasi");
            bg_konfirmasi.setVisible(true);
        } else {
            konfirmasi2.setEnabled(false);
            ketkonfirmasi.setText("");
            bg_konfirmasi.setVisible(false);
        }
    }//GEN-LAST:event_persetujuanActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        halkonfirmasi.setVisible(false);
        halreg.setVisible(true);
        konfirmasi2.setEnabled(false);
        ketkonfirmasi.setText("");
        bg_konfirmasi.setVisible(false);
        persetujuan.setSelected(false);
    }//GEN-LAST:event_kembaliActionPerformed

    private void konfirmasi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfirmasi2ActionPerformed
        halreg.setVisible(false);
        halkonfirmasi.setVisible(false);
        halpenutup.setVisible(true);
        tm.start();
        
        textnama.setText("");
        textalamat.setText("");
        angkart.setText("");
        angkarw.setText("");
        textkelurahan.setText("");
        textkecamatan.setText("");
        textkota.setText("");
        angkatelp.setText("08xxxxxxxxx");
        angkatelp.setForeground(new Color(153,153,153));
        textasal.setText("");
        textplat.setText("");
        angkaplat.setText("");
        textplat2.setText("");
        namatest.setText("");
        rttest.setText("");
        kelurahantest.setText("");
        kecamatantest.setText("");
        kotatest.setText("");
        notelptest.setText("");
        plattexttest.setText("");
        angkaplattest.setText("");
    }//GEN-LAST:event_konfirmasi2ActionPerformed

    int i = 0;
    Timer tm = new Timer(100, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            progressred.setValue(i++);
            if(i >= 100){
                halreg.setVisible(true);
                halkonfirmasi.setVisible(false);
                halpenutup.setVisible(false);
                konfirmasi2.setEnabled(false);
                ketkonfirmasi.setText("");
                bg_konfirmasi.setVisible(false);
                persetujuan.setSelected(false);
                tm.stop();
                progressred.setValue(i = 0);
            } 
        }
    });


    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int opsi = JOptionPane.showOptionDialog(null, " Apakah Anda Yakin\n Ingin Menghapus\n Semuanya?", "Bersihkan Form", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        switch(opsi){
            case JOptionPane.OK_OPTION:
                textnama.setText("");
                textalamat.setText("");
                angkart.setText("");
                angkarw.setText("");
                textkelurahan.setText("");
                textkecamatan.setText("");
                textkota.setText("");
                angkatelp.setText("08xxxxxxxxx");
                angkatelp.setForeground(new Color(153,153,153));
                textasal.setText("");
                textplat.setText("");
                angkaplat.setText("");
                textplat2.setText("");
                namatest.setText("");
                rttest.setText("");
                rwtest.setText("");
                kelurahantest.setText("");
                kecamatantest.setText("");
                kotatest.setText("");
                notelptest.setText("");
                plattexttest.setText("");
                angkaplattest.setText("");
                cleaner();
                break;
            case JOptionPane.NO_OPTION:
                break;
        }
    }//GEN-LAST:event_hapusActionPerformed

    public void cleaner(){
        textnama.setBorder(new LineBorder(Color.GRAY, 2));
        angkart.setBorder(new LineBorder(Color.GRAY, 2));
        angkarw.setBorder(new LineBorder(Color.GRAY, 2));
        textkelurahan.setBorder(new LineBorder(Color.GRAY, 2));
        textkecamatan.setBorder(new LineBorder(Color.GRAY, 2));
        textkota.setBorder(new LineBorder(Color.GRAY, 2));
        angkatelp.setBorder(new LineBorder(Color.GRAY, 2));
        textplat.setBorder(new LineBorder(Color.GRAY, 2));
        angkaplat.setBorder(new LineBorder(Color.GRAY, 2));
        textplat2.setBorder(new LineBorder(Color.GRAY, 2));
    }
    
    private void angkatelpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_angkatelpFocusGained
        if(angkatelp.getText().trim().equals("08xxxxxxxxx")) {
            angkatelp.setText("");
            angkatelp.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_angkatelpFocusGained

    private void angkatelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angkatelpActionPerformed
        
    }//GEN-LAST:event_angkatelpActionPerformed

    private void angkatelpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_angkatelpFocusLost
        if(angkatelp.getText().trim().equals("") || 
            angkatelp.getText().trim().toLowerCase().equals("08xxxxxxxxx")) {
            angkatelp.setText("08"+"xxxxxxxxx");
            angkatelp.setForeground(new Color(153,153,153));
            notelptest.setText("");
        }
    }//GEN-LAST:event_angkatelpFocusLost

    private void angkartKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angkartKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_angkartKeyTyped

    private void angkarwKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angkarwKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_angkarwKeyTyped

    private void angkatelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angkatelpKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_angkatelpKeyTyped

    private void angkaplatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_angkaplatKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_angkaplatKeyTyped

    private void catatan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catatan1MouseClicked
        
    }//GEN-LAST:event_catatan1MouseClicked

    public boolean verifyField() {
        String tnama = textnama.getText();
        String talamat = textalamat.getText();
        String art = angkart.getText();
        String arw = angkarw.getText();
        String tkelurahan = textkelurahan.getText();
        String tkecamatan = textkecamatan.getText();
        String tkota = textkota.getText();
        String atelp = angkatelp.getText();
        String ttipe = textasal.getText();
        String tplat = textplat.getText();
        String aplat = angkaplat.getText();
        String tplat2 = textplat2.getText();
        String namat = namatest.getText();
        String rtt = rttest.getText();
        String rwt = rwtest.getText();
        String kelurahant = kelurahantest.getText();
        String kecamatant = kecamatantest.getText();
        String kotat = kotatest.getText();
        String notelpt = notelptest.getText();
        String plattextt = plattexttest.getText();
        String angkaplatt = angkaplattest.getText();
        
        if(tnama.trim().equals("") || talamat.trim().equals("") || art.trim().equals("")
            || arw.trim().equals("") || tkelurahan.trim().equals("") || tkecamatan.trim().equals("")
            || tkota.trim().equals("") || atelp.trim().equals("08xxxxxxxxx") || ttipe.trim().equals("") || tplat.trim().equals("")
            || aplat.trim().equals("") || tplat2.trim().equals("") || !namat.trim().equals("")
            || !rtt.trim().equals("") || !rwt.trim().equals("") || !kelurahant.trim().equals("")
            || !kecamatant.trim().equals("") || !kotat.trim().equals("") || !notelpt.trim().equals("")
            || !plattextt.trim().equals("") || !angkaplatt.trim().equals("")) {
            
            JOptionPane.showMessageDialog(null, "Harap cek kembali data yang diisikan","Peringatan",2);
            return false;
        } else {
            return true;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    class PatternCheck extends MainWindow{
        private String pattern;
        private String input;

        public PatternCheck(String pattern, String input) {
            this.pattern = pattern;
            this.input = input;
        }

        public String cekinput(String ket) {
            Pattern patt = Pattern.compile(pattern);
            Matcher match = patt.matcher(input);
            if (!match.matches()) {
                return ket + " Tidak Valid";
            } else {
                return "";
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RT;
    private javax.swing.JLabel RW;
    private javax.swing.JLabel akronim;
    private javax.swing.JLabel alamat;
    private javax.swing.JTextField angkaplat;
    public javax.swing.JLabel angkaplattest;
    private javax.swing.JTextField angkart;
    private javax.swing.JTextField angkarw;
    private javax.swing.JTextField angkatelp;
    public javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JLabel bg4;
    private javax.swing.JLabel bg_konfirmasi;
    private javax.swing.JLabel bg_putih1;
    private javax.swing.JLabel bgalamat;
    private javax.swing.JLabel bginfo;
    private javax.swing.JLabel bgjudul;
    private javax.swing.JLabel bgkabkota;
    private javax.swing.JLabel bgkecamatan;
    private javax.swing.JLabel bgkelurahan;
    private javax.swing.JLabel bgnama;
    private javax.swing.JLabel bgnotelp;
    private javax.swing.JLabel bgplat;
    private javax.swing.JLabel bgrtrw;
    private javax.swing.JLabel bgtipe;
    private javax.swing.JLabel bgtitle;
    public javax.swing.JLabel calamat;
    public javax.swing.JLabel cangkaplat;
    private javax.swing.JLabel catatan1;
    private javax.swing.JLabel catatan2;
    public javax.swing.JLabel ckabkota;
    public javax.swing.JLabel ckecamatan;
    public javax.swing.JLabel ckelurahan;
    public javax.swing.JLabel cnama;
    public javax.swing.JLabel cnotelp1;
    public javax.swing.JLabel crt;
    public javax.swing.JLabel crw;
    private javax.swing.JLabel ctextcatatan;
    private javax.swing.JLabel ctextnama;
    public javax.swing.JLabel ctextplat1;
    public javax.swing.JLabel ctextplat2;
    public javax.swing.JLabel ctipe;
    private javax.swing.JTextArea deskripsi;
    public javax.swing.JLayeredPane halkonfirmasi;
    public javax.swing.JLayeredPane halpenutup;
    public javax.swing.JLayeredPane halreg;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel infoalamat;
    private javax.swing.JLabel infokabkota;
    private javax.swing.JLabel infokecamatan;
    private javax.swing.JLabel infokelurahan;
    private javax.swing.JLabel infonama;
    private javax.swing.JLabel infonotelp;
    private javax.swing.JLabel infoplat;
    private javax.swing.JLabel infoprogress;
    private javax.swing.JLabel infort;
    private javax.swing.JLabel inforw;
    private javax.swing.JLabel infotipe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judulpenutup;
    private javax.swing.JLabel kecamatan;
    public javax.swing.JLabel kecamatantest;
    private javax.swing.JLabel kelurahan;
    public javax.swing.JLabel kelurahantest;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel ketkonfirmasi;
    private javax.swing.JButton konfirmasi2;
    private javax.swing.JLabel kota;
    public javax.swing.JLabel kotatest;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel namabengkel;
    public javax.swing.JLabel namatest;
    private javax.swing.JLabel notelp;
    public javax.swing.JLabel notelptest;
    private javax.swing.JCheckBox persetujuan;
    private javax.swing.JLabel platno;
    public javax.swing.JLabel plattexttest;
    private javax.swing.JProgressBar progressred;
    public javax.swing.JLabel rttest;
    public javax.swing.JLabel rwtest;
    private javax.swing.JLabel terimakasih;
    private javax.swing.JTextField textalamat;
    private javax.swing.JTextField textasal;
    private javax.swing.JTextField textkecamatan;
    private javax.swing.JTextField textkelurahan;
    private javax.swing.JTextField textkota;
    private javax.swing.JTextField textnama;
    private javax.swing.JTextField textplat;
    private javax.swing.JTextField textplat2;
    private javax.swing.JLabel tipe;
    public static javax.swing.JButton tombolkonfirmasi;
    private javax.swing.JLabel ucapan;
    // End of variables declaration//GEN-END:variables

}
